// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1sdTKR9q6QepphtwD2DPZqyGSnjs5mYo',
    appId: '1:588910638568:android:e9f09c2b4bb9ddbc88605d',
    messagingSenderId: '588910638568',
    projectId: 'spendio-378dd',
    storageBucket: 'spendio-378dd.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE8k23cSxcKIroDZdlVbbi5HiQTYGzeng',
    appId: '1:588910638568:web:df8dfe1ac71fa9f888605d',
    messagingSenderId: '588910638568',
    projectId: 'spendio-378dd',
    authDomain: 'spendio-378dd.firebaseapp.com',
    storageBucket: 'spendio-378dd.firebasestorage.app',
    measurementId: 'G-NXNJVF3R6V',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE8k23cSxcKIroDZdlVbbi5HiQTYGzeng',
    appId: '1:588910638568:web:1e3a085a0d71e89288605d',
    messagingSenderId: '588910638568',
    projectId: 'spendio-378dd',
    authDomain: 'spendio-378dd.firebaseapp.com',
    storageBucket: 'spendio-378dd.firebasestorage.app',
    measurementId: 'G-K6R202E185',
  );
}
